#!/bin/sh

wget -q https://raw.githubusercontent.com/ideascube/ansiblecube/TM-autodeploy/tools/start_buildmycube.sh -O /tmp/start_buildmycube.sh
chmod +x /tmp/start_buildmycube.sh

nohup sh /tmp/start_buildmycube.sh ideasbox &

cat > /etc/rc.local <<EOF
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

exit 0
EOF
